import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {EventEmitter} from 'node:events';
import {snapshot,atomic,recordObservation,recordCooking,saveReceipt,validatePanel,recordAppNote,hash} from '../companion/domain.mjs';import {createCompanion} from '../companion/server.mjs';
import {CodexProvider} from '../companion/providers/codex.mjs';
import {shoppingIntent} from '../companion/jobs.mjs';
import {DatabaseSync} from 'node:sqlite';import {Store} from '../companion/store.mjs';
const root=path.resolve(import.meta.dirname,'..');
function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'garden-test-'));atomic(path.join(dir,'household.json'),{schema_version:1,id:'home',name:'Test kitchen',person:{id:'owner',name:'You'},timezone:'UTC',shopping:{list_service:'samsung_food',list_name:'Sample List',store:{chain:'Sample Market',label:'Central',address:'1 Example Road'}}});fs.mkdirSync(path.join(dir,'recipes/r'),{recursive:true});atomic(path.join(dir,'recipes/r/recipe.json'),{id:'r',title:'Test recipe',readiness:'ready',revision:1,ingredients:[],steps:[]});fs.mkdirSync(path.join(dir,'data/plans'),{recursive:true});return dir}
test('catalog preserves readiness; old plans and unknown stock remain distinct',()=>{const real=snapshot(path.join(root,'sample-household'));assert.ok(real.recipes.length>0);for(const recipe of real.recipes.filter(r=>r.readiness==='ready')){assert.ok(recipe.ingredients.length>0);assert.ok(recipe.steps.length>0);}const r=fixture();try{atomic(path.join(r,'data/inventory/current.json'),{status:'not_inventoried',lots:[]});atomic(path.join(r,'data/plans/test.json'),{id:'test',status:'active',meals:[{date:'1900-01-01',recipe_id:'r'}]});const old=snapshot(r);assert.equal(old.planIsPast,true);assert.equal(old.inventory.status,'not_inventoried');atomic(path.join(r,'data/plans/test.json'),{id:'test',status:'active',meals:[{date:'9999-01-01',recipe_id:'r'}]});assert.equal(snapshot(r).planIsPast,false);}finally{fs.rmSync(r,{recursive:true,force:true})}});
test('observations, cooking and receipts are idempotent and do not deduct inventory',()=>{const r=fixture();try{const input={item:'Spinach',note:'Looks sound; use or freeze soon',quantityState:'unknown',quantityEstimate:{value:12,unit:'oz',certainty:'rough estimate'},bestIfUsedBy:'2026-09-25',preservationNeed:'consider_use_or_freeze',condition:'use_soon',location:'fridge',idempotencyKey:'same'};const first=recordObservation(r,input);assert.deepEqual(recordObservation(r,input),first);assert.equal(first.quantityEstimate.value,12);assert.equal(first.preservationNeed,'consider_use_or_freeze');assert.equal(recordObservation(r,{...input,idempotencyKey:'discard',condition:'discard'}).preservationNeed,null);assert.equal(fs.readdirSync(path.join(r,'data/observations')).length,2);assert.equal(fs.existsSync(path.join(r,'data/inventory/current.json')),false);const c=recordCooking(r,{recipeId:'r',note:'Made half; yield unknown',idempotencyKey:'cook'});assert.equal(c.inventoryReconciled,false);assert.throws(()=>recordCooking(r,{recipeId:'../../etc',note:'x',idempotencyKey:'x'}));const receipt={store:'Sample Market',date:'2026-09-25',fingerprint:'receipt-test',source:'fixture',items:[{name:'Tofu',quantity:'1',price:2}],total:2};assert.equal(saveReceipt(r,receipt).id,saveReceipt(r,receipt).id);assert.equal(fs.readdirSync(path.join(r,'data/receipts')).length,1);assert.throws(()=>saveReceipt(r,{...receipt,date:'yesterday'}));}finally{fs.rmSync(r,{recursive:true,force:true})}});
test('native panels allow only validated recipe links and user-tapped prompts',()=>{const r=fixture();try{assert.equal(validatePanel({title:'Cook',body:'Try this',actions:[{label:'Open',type:'recipe',value:'r'}]},r).actions.length,1);assert.throws(()=>validatePanel({title:'x',body:'x',actions:[{label:'Run',type:'script',value:'evil'}]},r));assert.throws(()=>validatePanel({title:'x',body:'x',actions:[{label:'Open',type:'recipe',value:'missing'}]},r));}finally{fs.rmSync(r,{recursive:true,force:true})}});
test('app feedback saves full long text and metadata as an idempotent local record',()=>{const r=fixture();try{const note={id:'e5ac3428-3f94-4af2-9ddb-8de41b49124e',text:'  Opening thought.\n'+('A long dictated note with spinach and meals. '.repeat(1500))+'\nFinal thought.  ',phoneTime:'2026-09-26T18:30:00-07:00',screen:'Kitchen reset',target:'Spot at 42%, 60%',position:{x:0.42,y:0.6},appVersion:'0.0.6',device:'Pixel'};const first=recordAppNote(r,note),disk=JSON.parse(fs.readFileSync(path.join(r,'data/app-feedback',note.id+'.json'),'utf8'));assert.deepEqual(recordAppNote(r,note),first);assert.equal(disk.text,note.text);assert.equal(disk.phoneTime,note.phoneTime);assert.equal(disk.screen,note.screen);assert.equal(disk.target,note.target);assert.deepEqual(disk.position,note.position);assert.equal(disk.device,note.device);assert.equal(disk.appVersion,note.appVersion);assert.equal(fs.readdirSync(path.join(r,'data/app-feedback')).length,1);assert.equal(first.source,'You via Meal Garden · no model call');assert.throws(()=>recordAppNote(r,{...note,text:'Changed after save'}),/different content/);assert.throws(()=>recordAppNote(r,{...note,id:'../etc/passwd'}));}finally{fs.rmSync(r,{recursive:true,force:true})}});
test('feedback screen images remain separate, bounded and linked to their exact note and build',()=>{const r=fixture();try{const bytes=Buffer.from([0xff,0xd8,0xff,0xd9]),sha=hash(bytes),apkSha=hash('apk'),note={id:'e7ac3428-3f94-4af2-9ddb-8de41b49124e',text:'Please change this card',phoneTime:'2026-09-26T18:30:00-07:00',screen:'Kitchen reset',appVersion:'0.0.7',appVersionCode:8,apkSha256:apkSha,screenContext:{route:'fridge-check',title:'Kitchen reset',sourceFile:'app/android/app/src/main/java/app/mealgarden/FridgeCheckScreen.kt',capturedAt:'2026-09-26T18:29:59-07:00',tab:'Today',appVersionCode:8,apkSha256:apkSha,captureStatus:'captured'},screenshot:{sha256:sha,width:1080,height:2404,capturedAt:'2026-09-26T18:29:59-07:00'},screenshotData:bytes.toString('base64')};const saved=recordAppNote(r,note),image=path.join(r,saved.screenshot.path),disk=JSON.parse(fs.readFileSync(path.join(r,'data/app-feedback',note.id+'.json'),'utf8'));assert.equal(saved.schema_version,2);assert.equal(saved.screenContext.route,'fridge-check');assert.equal(saved.screenContext.sourceFile,note.screenContext.sourceFile);assert.equal(saved.appVersionCode,8);assert.equal(saved.apkSha256,apkSha);assert.equal(saved.screenshot.sha256,sha);assert.deepEqual(fs.readFileSync(image),bytes);assert.equal(disk.screenshotData,undefined);assert.deepEqual(recordAppNote(r,note),saved);assert.throws(()=>recordAppNote(r,{...note,text:'Different'}),/different content/);assert.throws(()=>recordAppNote(r,{...note,id:'e8ac3428-3f94-4af2-9ddb-8de41b49124e',screenshotData:'AAAA'}),/invalid|missing/);}finally{fs.rmSync(r,{recursive:true,force:true})}});
async function waitFor(predicate,timeout=2000){const deadline=Date.now()+timeout;while(!predicate()){if(Date.now()>=deadline)throw new Error('Timed out waiting for the synthetic provider');await new Promise(resolve=>setTimeout(resolve,5));}}
class FakeProvider extends EventEmitter{constructor(){super();this.threadModels=new Map()}async thread(...args){this.threadArgs=args;this.threadModels.set('thread-test',args[3]);return 'thread-test'}async start(...args){this.startArgs=args;return {turn:{id:'turn-test'}}}async cancel(){this.emit('event',{method:'turn/completed',params:{threadId:'thread-test',turn:{status:'interrupted'}}})}respond(id,response){this.last={id,response}}reject(){}close(){}}
test('shopping launches only with a fresh verified model thread',async()=>{const r=fixture(),provider=new FakeProvider(),app=createCompanion({root:r,runtime:path.join(r,'.runtime'),provider});try{atomic(path.join(r,'data/plans/current.json'),{id:'current',status:'active',meals:[{date:'9999-01-01'}]});atomic(path.join(r,'data/shopping/current-trip.json'),{id:'trip',plan_id:'current',buy:[{name:'Tofu',quantity:1,unit:'pack'}]});const job=app.jobs.enqueue({kind:'shopping',requestKey:'shopping-model-check'});await waitFor(()=>provider.startArgs);assert.equal(job.model,'gpt-6.1-sol');assert.equal(app.store.get('SELECT model FROM jobs WHERE id=?',job.id).model,'gpt-6.1-sol');assert.equal(provider.threadArgs[0],null);assert.equal(provider.threadArgs[3],'gpt-6.1-sol');assert.equal(provider.threadArgs[4],true);assert.equal(provider.startArgs[2],'gpt-6.1-sol');assert.equal(provider.startArgs[4],true);assert.equal(app.store.get('SELECT observed_model FROM jobs WHERE id=?',job.id).observed_model,'gpt-6.1-sol');provider.emit('event',{method:'model/rerouted',params:{threadId:'thread-test',turnId:'turn-test',fromModel:'gpt-6.1-sol',toModel:'gpt-6-luna',reason:'fixture'}});await new Promise(resolve=>setTimeout(resolve,5));assert.equal(app.store.get('SELECT status FROM jobs WHERE id=?',job.id).status,'failed');assert.equal(app.store.get('SELECT observed_model FROM jobs WHERE id=?',job.id).observed_model,'gpt-6-luna');}finally{app.close();fs.rmSync(r,{recursive:true,force:true})}});
test('audit migration preserves old conversations and records per-job provenance',()=>{const r=fixture(),file=path.join(r,'.runtime/garden.sqlite');fs.mkdirSync(path.dirname(file),{recursive:true});const old=new DatabaseSync(file);old.exec("CREATE TABLE conversations(id TEXT PRIMARY KEY,title TEXT NOT NULL,provider_id TEXT,created TEXT NOT NULL);CREATE TABLE messages(id TEXT PRIMARY KEY,conversation_id TEXT NOT NULL,role TEXT NOT NULL,text TEXT NOT NULL,created TEXT NOT NULL,panels TEXT NOT NULL DEFAULT '[]');CREATE TABLE jobs(id TEXT PRIMARY KEY,request_key TEXT UNIQUE NOT NULL,conversation_id TEXT NOT NULL,kind TEXT NOT NULL,status TEXT NOT NULL,input TEXT NOT NULL,model TEXT,created TEXT NOT NULL,updated TEXT NOT NULL,error TEXT,turn_id TEXT,progress TEXT);");old.prepare('INSERT INTO conversations VALUES(?,?,?,?)').run('old','Earlier conversation',null,'2026-09-01');old.prepare('INSERT INTO messages VALUES(?,?,?,?,?,?)').run('old-message','old','user','Keep this', '2026-09-01','[]');old.close();const s=new Store(file);try{assert.equal(s.messages('old')[0].text,'Keep this');assert.deepEqual(s.messages('old')[0].metadata,{});const c=s.conversation('New','android_app');const m=s.message(c.id,'user','Dinner?',[], 'job-1',{clientSentAt:'2026-09-26T19:00:00-07:00'});s.event('job-1','queued',{model:'gpt-6.1-sol'});assert.equal(s.get('SELECT source FROM conversations WHERE id=?',c.id).source,'android_app');assert.equal(s.messages(c.id)[0].metadata.clientSentAt,'2026-09-26T19:00:00-07:00');assert.equal(s.get('SELECT type FROM job_events WHERE job_id=?','job-1').type,'queued');assert.equal(m.job_id,'job-1');}finally{s.close();fs.rmSync(r,{recursive:true,force:true})}});
test('attached photos remain linked to completed conversations',async()=>{const r=fixture(),runtime=path.join(r,'.runtime'),provider=new FakeProvider(),app=createCompanion({root:r,runtime,provider});app.store.run('INSERT INTO devices VALUES(?,?,?)',hash('photo-test'),'Pixel','now');await new Promise(resolve=>app.server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${app.server.address().port}`;const post=async(route,data)=>{const response=await fetch(base+route,{method:'POST',headers:{Authorization:'Bearer photo-test','Content-Type':'application/json'},body:JSON.stringify(data)});assert.ok(response.ok);return response.json()};try{const photo=await post('/api/upload',{data:Buffer.from([255,216,255,217]).toString('base64')});const job=await post('/api/jobs',{requestKey:'photo-job',text:'What is in this photo?',attachmentIds:[photo.id]});await new Promise(resolve=>setTimeout(resolve,20));provider.emit('event',{method:'turn/completed',params:{threadId:'thread-test',turn:{status:'completed'}}});assert.equal(app.store.get('SELECT status FROM attachments WHERE id=?',photo.id).status,'archived');assert.equal(app.store.get('SELECT job_id FROM attachments WHERE id=?',photo.id).job_id,job.id);assert.equal(fs.existsSync(path.join(runtime,'attachments',photo.id+'.jpg')),true);}finally{app.close();fs.rmSync(r,{recursive:true,force:true})}});
test('shopping-list follow-up chat is also classified for strict model verification',()=>{assert.equal(shoppingIntent('Please add it as an item on the list'),true);assert.equal(shoppingIntent('What aisle is the yogurt in?'),true);assert.equal(shoppingIntent('How should I cook the tofu?'),false)});
test('model mismatch restarts before any shopping turn and retries the requested model once',async()=>{const p=new CodexProvider(root);let starts=0,restarts=0,turns=0;p.connect=async()=>{p.models=[{model:'gpt-6.1-sol'}];return p};p.restartForModelMismatch=()=>{restarts++;p.verifiedModels.clear()};p.request=async(method)=>{if(method==='thread/start'){starts++;return {thread:{id:'thread-'+starts,model:starts===1?'gpt-6-luna':'gpt-6.1-sol'}}}if(method==='thread/read')return {thread:{model:starts===1?'gpt-6-luna':'gpt-6.1-sol'}};if(method==='turn/start'){turns++;return {turn:{id:'turn'}}}throw new Error(method)};const thread=await p.thread(null,[],'','gpt-6.1-sol',true);assert.equal(restarts,1);assert.equal(starts,2);assert.equal(turns,0);await p.start(thread,'shop','gpt-6.1-sol',[],true);assert.equal(turns,1);assert.equal(p.verifiedModels.get(thread),'gpt-6.1-sol')});
test('HTTP auth, duplicate jobs, streaming, native cards, approvals, and interrupted-job recovery',async()=>{const r=fixture(),runtime=path.join(r,'.runtime'),provider=new FakeProvider(),app=createCompanion({root:r,runtime,provider});app.store.run('INSERT INTO devices VALUES(?,?,?)',hash('test-only'),'test','now');await new Promise(resolve=>app.server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${app.server.address().port}`;const req=async(route,body,auth=true)=>{const res=await fetch(base+route,{method:body?'POST':'GET',headers:{...(auth?{Authorization:'Bearer test-only'}:{}),...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});return {status:res.status,body:await res.json()}};
 try{
  assert.equal((await req('/api/snapshot',null,false)).status,401);
  const feedback={id:'f2fc9304-219e-4c86-8c88-39b354a78a29',text:'The ingredient check needs a clearer label',phoneTime:'2026-09-26T18:30:00-07:00',screen:'Kitchen reset',target:'Use soon',position:{x:0.2,y:0.6}};
  assert.equal((await req('/api/feedback',feedback,false)).status,401);
  assert.equal((await req('/api/feedback',feedback)).status,201);
  assert.equal((await req('/api/feedback',feedback)).status,201);
  const longFeedback={...feedback,id:'13b25394-4b54-4af2-9ddb-8de41b49124e',text:'Long note: '+('At the store, remember the meal plan. '.repeat(2000))};
  const longResponse=await req('/api/feedback',longFeedback);assert.equal(longResponse.status,201);assert.equal(longResponse.body.text,longFeedback.text);assert.equal(JSON.parse(fs.readFileSync(path.join(r,'data/app-feedback',longFeedback.id+'.json'),'utf8')).text,longFeedback.text);
  assert.equal(fs.readdirSync(path.join(r,'data/app-feedback')).length,2);
  const malicious=await fetch(base+'/api/activity',{headers:{Authorization:'Bearer test-only',Origin:'https://evil.example'}});assert.equal(malicious.status,403);
  const input={requestKey:'one',text:'test',client:{origin:'chat_composer',composeStartedAt:'2026-09-26T18:30:00-07:00',clientSentAt:'2026-09-26T18:31:00-07:00',uiModelAtCompose:'gpt-6.1-sol',uiModelAtSend:'gpt-6.1-sol',sendScreen:'Chat'}};const a=await req('/api/jobs',input),b=await req('/api/jobs',input);assert.equal(a.status,202);assert.equal(a.body.id,b.body.id);await new Promise(r=>setTimeout(r,25));assert.equal(app.store.jobs().length,1);assert.equal(app.store.jobs()[0].metadata.clientSentAt,'2026-09-26T18:31:00-07:00');assert.equal(app.store.jobs()[0].observed_model,'gpt-6.1-sol');assert.match(app.store.jobs()[0].prompt,/Current local date and time for You:/);assert.equal(app.store.get('SELECT count(*) n FROM job_events WHERE job_id=?',a.body.id).n>2,true);
  provider.emit('event',{method:'item/agentMessage/delta',params:{threadId:'thread-test',itemId:'msg',delta:'Hello'}});
  provider.emit('event',{method:'item/completed',params:{threadId:'thread-test',item:{id:'msg',type:'agentMessage',text:'Hello You'}}});
  provider.emit('request',{id:9,method:'item/tool/call',params:{threadId:'thread-test',tool:'meal_garden_card',arguments:{title:'Recipe',body:'A native card',actions:[{label:'Open',type:'recipe',value:'r'}]}}});assert.equal(provider.last.response.success,true);
  provider.emit('request',{id:10,method:'item/tool/requestUserInput',params:{threadId:'thread-test',questions:[{id:'q',question:'Choose?',options:[]}]}});const pending=[...app.jobs.requests.values()][0];assert.ok(pending);assert.equal((await req('/api/answer',{id:pending.id,answers:{q:'A'}})).status,200);assert.deepEqual(provider.last.response,{answers:{q:{answers:['A']}}});
  provider.emit('event',{method:'turn/completed',params:{threadId:'thread-test',turn:{status:'completed'}}});assert.equal(app.store.jobs()[0].status,'completed');const msgs=app.store.messages(a.body.conversation_id);assert.equal(msgs.find(x=>x.role==='assistant').text,'Hello You');assert.equal(msgs.find(x=>x.role==='card').panels[0].actions[0].value,'r');
  const external=await req('/api/jobs',{requestKey:'external',kind:'purchases'});await new Promise(r=>setTimeout(r,25));provider.emit('event',{method:'turn/completed',params:{threadId:'thread-test',turn:{status:'completed'}}});assert.equal(app.store.get('SELECT status FROM jobs WHERE id=?',external.body.id).status,'unverified');
  const multi=await req('/api/jobs',{requestKey:'multi',kind:'connection'});await new Promise(r=>setTimeout(r,25));
  for(const status of ['needs_sign_in','completed'])provider.emit('request',{id:11,method:'item/tool/call',params:{threadId:'thread-test',tool:'meal_garden_job_result',arguments:{status,summary:status,evidence:'Fixture observation'}}});
  provider.emit('event',{method:'turn/completed',params:{threadId:'thread-test',turn:{status:'completed'}}});assert.equal(app.store.get('SELECT status FROM jobs WHERE id=?',multi.body.id).status,'needs_sign_in');
  await req('/api/jobs',{requestKey:'crash',text:'Interrupted work'});await new Promise(r=>setTimeout(r,25));
 }finally{app.close()}
 const recovered=createCompanion({root:r,runtime,provider:new FakeProvider()});assert.equal(recovered.store.jobs().find(j=>j.request_key==='crash').status,'interrupted');recovered.close();fs.rmSync(r,{recursive:true,force:true});
});
